version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    deploy:
      restart_policy: # bad workaround, just to simplify the demo.
        condition: on-failure
  collector-gateway:
    image: otel/opentelemetry-collector:0.29.0
    volumes:
      - ./config/collector-gateway.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "13133:13133" # health_check extension
      - "4320:4320"        # OTLP gRPC receiver
      - "4319:4319"        # OTLP HTTP receiver
  collector-agent:
    image: otel/opentelemetry-collector:0.29.0
    volumes:
      - ./config/collector-agent.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"        # OTLP HTTP receiver